apiVersion: dbo.dosquad.github.io/v1
kind: DatabaseAccountControllerConfig
dsn: "postgres://postgres:mysecretpassword@localhost:5432/"
metrics:
  bindAddress: 0.0.0.0:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: ade51e3.dosquad.github.io
