name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: "Unit Test"
    uses: dosquad/actions/.github/workflows/unit-test.yml@main
    secrets: inherit
    with:
      platforms: 'linux/amd64,linux/arm64'
