name: "Docker Release"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker:
    name: "Docker"
    uses: dosquad/actions/.github/workflows/docker-release.yml@main
    with:
      image: ghcr.io/dosquad/database-operator
      platforms: 'linux/amd64,linux/arm64'
    secrets: inherit
