name: Cleanup on Closed Pull Request

on:
  pull_request:
    types: 
      - closed

jobs:
  docker:
    name: "Docker Cleanup"
    uses: dosquad/actions/.github/workflows/docker-pr-cleanup.yml@main
    with:
      package-name: database-operator
      owner: "${{github.repository_owner}}"
      pull-request-merged: "${{github.event.inputs.pull-request-merged}}"
      pull-request-number: "${{github.event.pull_request.number}}"
    secrets: inherit
